#!/usr/bin/env node
/**
 * Downloads the brand webfonts into src/styles/fonts/ and writes
 * src/styles/fonts.css pointing at the local copies.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Why self-host rather than link to Google Fonts:
 *  - a render-blocking request to a third-party CDN is the single largest
 *    thing standing between a visitor and first paint;
 *  - if that CDN is slow or filtered — which happens on corporate and some
 *    regional networks — the whole page waits on it;
 *  - nothing about a visitor is sent to a third party.
 *
 * Only the latin and latin-ext subsets are kept; this is an English site.
 * Re-run only when changing typefaces. Output is committed.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const API = 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap';
const KEEP = new Set(['latin', 'latin-ext']);

const css = await fetch(API, { headers: { 'User-Agent': UA } }).then((r) => r.text());
await mkdir('src/styles/fonts', { recursive: true });

const blocks = css.split('@font-face').slice(1).map((b) => '@font-face' + b.split('}')[0] + '}');
const out = [];
let subset = null;
let kept = 0;
const seen = new Set();

// The API emits `/* latin */` comments before each block; track the latest.
for (const line of css.split('\n')) {
  const m = line.match(/^\s*\/\*\s*([a-z-]+)\s*\*\/\s*$/);
  if (m) subset = m[1];
  if (!line.includes('@font-face')) continue;
  const block = blocks.shift();
  if (!block || !subset || !KEEP.has(subset)) continue;

  const url = block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
  if (!url) continue;

  // Variable-font families serve one identical file for every weight, so
  // deduplicate on content rather than committing the same bytes five times.
  const buf = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()));
  const digest = createHash('sha256').update(buf).digest('hex').slice(0, 8);
  const name = `${family.toLowerCase().replace(/\s+/g, '-')}-${subset}-${digest}.woff2`;
  if (!seen.has(name)) {
    await writeFile(`src/styles/fonts/${name}`, buf);
    seen.add(name);
    kept++;
  }

  out.push(block.replace(/url\([^)]+\)/, `url('./fonts/${name}')`).replace(/;\s*$/, '').trim());
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted so first paint never waits on a third-party CDN.
   The files live in src/ so Vite fingerprints them and rewrites these
   URLs with the configured base — correct in any nested folder. */\n\n`;

await writeFile('src/styles/fonts.css', header + out.join('\n\n') + '\n', 'utf8');
console.log(`✓ ${kept} unique font files -> src/styles/fonts/ (${out.length} @font-face rules)`);
console.log('✓ src/styles/fonts.css');
