#!/usr/bin/env node
/**
 * Builds the drop-in XAMPP package: the static site, the admin panel, the
 * API and a web installer, laid out as one folder to copy into htdocs.
 *
 *   node scripts/package-xampp.mjs            # folder name: errorsfree
 *   FOLDER=mysite node scripts/package-xampp.mjs
 *
 * Produces errorsfree-xampp.zip containing:
 *
 *   errorsfree/
 *   ├── index.html, about/, blog/, case-studies/, …   the static site
 *   ├── admin/          the panel
 *   ├── api/            JSON API
 *   ├── uploads/        images added through the panel
 *   ├── _backend/       code + schema + seed, denied over HTTP
 *   └── setup.php       one-time installer, delete after use
 *
 * The site is built with SITE_BASE matching the folder, so every link
 * resolves under http://localhost/<folder>/.
 */
import { execFileSync } from 'node:child_process';
import { cp, rm, mkdir, writeFile, readFile } from 'node:fs/promises';

const FOLDER = process.env.FOLDER ?? 'errorsfree';
const OUT = `${FOLDER}-xampp.zip`;
const STAGE = 'xampp-package';
const DIR = `${STAGE}/${FOLDER}`;

// Build the static site for this exact subfolder.
execFileSync('npx', ['astro', 'build'], {
  stdio: 'inherit',
  env: { ...process.env, SITE_BASE: `/${FOLDER}` },
});

await rm(STAGE, { recursive: true, force: true });
await mkdir(DIR, { recursive: true });

// 1. The static site at the folder root.
await cp('dist', DIR, { recursive: true });
await rm(`${DIR}/.htaccess`, { force: true });   // replaced below

// 2. Web-facing PHP: admin, api, uploads, the bootstrap shim, the installer.
await cp('backend/public', DIR, { recursive: true });

// 3. Everything else under _backend, which the .htaccess denies.
await mkdir(`${DIR}/_backend`, { recursive: true });
for (const part of ['src', 'bin', 'migrations', 'seed']) {
  await cp(`backend/${part}`, `${DIR}/_backend/${part}`, { recursive: true });
}
await cp('backend/.env.example', `${DIR}/_backend/.env.example`);
await cp('backend/README.md', `${DIR}/_backend/README.md`);

// Deny-all inside _backend, belt to the root .htaccess's braces.
await writeFile(`${DIR}/_backend/.htaccess`, [
  '# Application code, schema and configuration. Never served over HTTP.',
  'Require all denied',
  '',
].join('\n'));

// 4. Root .htaccess: clean URLs for the static pages, plus hard denials.
await writeFile(`${DIR}/.htaccess`, `# ErrorsFree — generated by scripts/package-xampp.mjs
Options -Indexes
DirectoryIndex index.html index.php

# Configuration and code must never be readable, wherever they end up.
<FilesMatch "^(\\.env.*|.*\\.sql|.*\\.md|composer\\.(json|lock))$">
  Require all denied
</FilesMatch>

<IfModule mod_headers.c>
  Header always set X-Content-Type-Options "nosniff"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml \\
    application/javascript application/json image/svg+xml
</IfModule>

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /${FOLDER}/

  # Leave the PHP entry points alone.
  RewriteRule ^(admin|api)(/|$) - [L]
  RewriteRule ^setup\\.php$ - [L]

  # /about -> /about/ so the static index.html is found.
  RewriteCond %{REQUEST_FILENAME} -d
  RewriteCond %{REQUEST_URI} !/$
  RewriteRule ^(.*)$ /${FOLDER}/$1/ [R=301,L]
</IfModule>

ErrorDocument 404 /${FOLDER}/404.html
`);

await writeFile(`${DIR}/READ-ME-FIRST.txt`, await readFile('scripts/xampp-readme.txt', 'utf8'));

await rm(OUT, { force: true });
// cwd is the stage directory, so one level up is the project root.
execFileSync('zip', ['-rq', `../${OUT}`, FOLDER], { cwd: STAGE, stdio: 'inherit' });

console.log(`\n✓ ${OUT}`);
console.log(`  Extract into XAMPP's htdocs, then open:`);
console.log(`    http://localhost/${FOLDER}/setup.php`);
console.log(`\n  dist/ now holds the /${FOLDER} build. Run \`npm run build\` before a cPanel deploy.`);
