#!/usr/bin/env node
/**
 * Writes dist/.htaccess after a build.
 *
 * It is generated rather than kept in public/ because Apache's
 * ErrorDocument needs an absolute URL path, which depends on the
 * SITE_BASE the site was built for. Building for a different folder
 * therefore produces a correct .htaccess with no manual edit.
 */
import { writeFile } from 'node:fs/promises';

const base = `/${(process.env.SITE_BASE ?? '/errorsfree').replace(/^\/+|\/+$/g, '')}/`.replace('//', '/');

const htaccess = `# ErrorsFree — generated by scripts/postbuild.mjs. Do not edit by hand.
# Built for base: ${base}

Options -Indexes
DirectoryIndex index.html

<IfModule mod_headers.c>
  Header always set X-Content-Type-Options "nosniff"
  Header always set X-Frame-Options "SAMEORIGIN"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
  Header always set Permissions-Policy "geolocation=(), microphone=(), camera=(), interest-cohort=()"
</IfModule>

# Hashed build assets never change under the same name.
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/css                 "access plus 1 year"
  ExpiresByType application/javascript   "access plus 1 year"
  ExpiresByType image/svg+xml            "access plus 6 months"
  ExpiresByType image/png                "access plus 6 months"
  ExpiresByType image/webp               "access plus 6 months"
  ExpiresByType text/html                "access plus 0 seconds"
</IfModule>

<IfModule mod_headers.c>
  <FilesMatch "\\.(css|js)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
  <FilesMatch "\\.html$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml \\
    application/javascript application/json application/xml image/svg+xml
</IfModule>

<IfModule mod_mime.c>
  AddType image/svg+xml .svg
  AddType application/manifest+json .webmanifest
</IfModule>

ErrorDocument 404 ${base}404.html

# Serve /about/ from /about/index.html and add the trailing slash when a
# directory is requested without one. Scoped to this folder only.
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase ${base}
  RewriteCond %{REQUEST_FILENAME} -d
  RewriteCond %{REQUEST_URI} !/$
  RewriteRule ^(.*)$ ${base}$1/ [R=301,L]
</IfModule>
`;

await writeFile('dist/.htaccess', htaccess, 'utf8');
console.log(`✓ dist/.htaccess written for base ${base}`);
